[package]
name = "modular-linear-recurrence-sequence-graphs"
version = "0.1.0"
authors = ["Benjamin Herman <benjamin@metanomial.com>"]
edition = "2021"

[dependencies]

[dependencies.clap]
version = "3.2.12"
features = ["derive"]
